name: CI (pytest) — services/dag

on:
  push:
    branches: [ main, master ]
    paths:
      - 'services/dag/**'
      - '.github/workflows/ci-dag.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'services/dag/**'
      - '.github/workflows/ci-dag.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dag
    strategy:
      matrix:
        python-version: ['3.10','3.11','3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (with coverage)
        env:
          PYTHONPATH: ${{ github.workspace }}/services/dag
        run: pytest
